# IMPORTANT: This code is fully generated by llm, we are gonna need to come up with visualizations for the backtest

# backtester/analysis.py
import pandas as pd

try:
    import pyfolio as pf  # You will need to: pip install pyfolio
except ImportError:  # pragma: no cover - optional dependency
    pf = None

# Import your Portfolio class
try:
    from .portfolio import Portfolio
except ImportError:
    print("Could not import Portfolio. Assuming it's in the same dir for testing.")
    pass 

def get_returns_from_equity_curve(equity_curve: list) -> pd.Series:
    """
    Converts the portfolio's list of (timestamp, value) tuples
    into a pandas Series of daily percentage returns.
    
    Pyfolio requires a Series of returns, not equity values.
    """
    if not equity_curve:
        return pd.Series(dtype=float)

    # 1. Create a DataFrame from the list
    df = pd.DataFrame(equity_curve, columns=['timestamp', 'total_value'])
    
    # 2. Set the timestamp as the index (required by pyfolio)
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df = df.set_index('timestamp')

    # 3. Ensure the index is timezone-naive (pyfolio requirement)
    df.index = df.index.tz_localize(None)

    # 4. Resample to daily frequency, taking the last value of each day
    # This handles intraday data (e.g., hourly bars)
    df_daily = df.resample('D').last()

    # 5. Fill missing days (weekends, holidays) with the previous day's value
    df_daily = df_daily.ffill()

    # 6. Calculate the daily percentage returns
    returns_series = df_daily['total_value'].pct_change().fillna(0)
    
    return returns_series

def generate_full_tear_sheet(portfolio: Portfolio, benchmark_returns: pd.Series = None):
    """
    Generates a full performance report using pyfolio.
    
    'portfolio' is the final Portfolio object returned from the engine.
    'benchmark_returns' is an optional Series of returns (e.g., SPY).
    """
    
    # 1. Get the returns from our portfolio's equity curve
    returns = get_returns_from_equity_curve(portfolio.equity_curve)
    
    if returns.empty:
        print("Equity curve is empty. Cannot generate report.")
        return

    if pf is None:
        print("Pyfolio is not installed; skipping tear sheet generation.")
        return

    print("--- Generating Performance Report (this may take a moment) ---")
    
    # 2. Use pyfolio to create the full report
    # This will generate a multi-page PDF with charts and stats
    pf.create_full_tear_sheet(
        returns,
        benchmark_rets=benchmark_returns
    )
    print("--- Report Generation Complete ---")
    
    # We can also return the stats dictionary
    # stats = pf.simple.perf_stats(returns)
    # return stats

def get_trade_log_df(portfolio: Portfolio) -> pd.DataFrame:
    """
    Converts the portfolio's trade_log (a list of FillEvents)
    into a clean pandas DataFrame for analysis.
    """
    if not portfolio.trade_log:
        return pd.DataFrame(columns=[
            'symbol', 'timestamp', 'quantity', 
            'fill_price', 'commission', 'signal'
        ])
    
    # Convert list of dataclass objects to a DataFrame
    # vars() turns a dataclass instance into a dict
    trade_df = pd.DataFrame([vars(fill) for fill in portfolio.trade_log])
    
    # Clean up
    trade_df['timestamp'] = pd.to_datetime(trade_df['timestamp'])
    trade_df = trade_df.set_index('timestamp').sort_index()
    
    return trade_df